language: go
sudo: false

before_script:
  - go vet ./...
  - diff <(gofmt -s -d ./timeinterval) <(printf "")

script:
  - go test -v ./...

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true
